### ISSUE TITLE
Mesh isotropy

### ISSUE THREAD

**Issue by yvanblanchard** [jamesgregson/remesher#1]
Hello,

I did a test using the remesher tool on a quite simple mesh, but it leads to bad triangle fact aspect, and isotropy is not so good (very sharp facets, larger triangle area locally,..): 
![image](https://user-images.githubusercontent.com/63931618/195905701-8aa30874-8e3b-46e6-a8f0-5f55d0e9a2f7.png)

Is it possible to tune this ?
thank you

**Comment by jamesgregson** [comment]
This is less a production quality tool than experimental code. It was inspired by reading in a paper that decent remeshing was possible by performing (approximate) Lloyd iterations on the vertices and then performing edge flips to improve minimum angle. I haven't looked at it in nearly a decade and it wasn't state of the art then. If you need very good quality I would recommend the CGAL remeshers.

That said: from the image, it looks like your edges are not subdivided as finely as your mesh. You could try tuning the edge-threshold, the element size or adjusting the code to fix this. I also tested this only on manifold meshes so if your mesh has open boundaries this may be part of the root cause and not well handled by the current implementation.
